### ISSUE TITLE
Improve table driven tests with sub tests

### ISSUE THREAD

**Issue by mungujn** [Lubwama-Emmanuel/scrapper_golang#2]
This [request](https://github.com/Lubwama-Emmanuel/scrapper_golang/pull/1#discussion_r1126090392) can be fulfilled with subtests. Refer to these resources

1. https://medium.com/@opheliaandcat/table-driven-and-individual-subtests-in-golang-which-one-to-use-360b5de39d
2. https://ieftimov.com/posts/testing-in-go-subtests/

**Comment by Lubwama-Emmanuel** [comment]
On it

**Comment by mungujn** [comment]
Will close once pipelines are fixed
